meta:
  environment: (( merge ))
  dns_root: (( merge ))
  security_groups: (( merge ))
  network_name: (( merge ))

  stemcell:
    name: bosh-aws-xen-ubuntu
    version: latest

jobs:
  - name: logstash-shipper_z1
    instances: 2
    networks:
      - name: (( meta.network_name ))
    properties: {}

compilation:
  cloud_properties:
    instance_type: m1.small

resource_pools:
  - name: small_z1
    cloud_properties:
      instance_type: m1.small

networks:
  - name: floating
    type: vip
    cloud_properties: {}
  - name: (( meta.network_name ))
    type: dynamic
    cloud_properties:
      security_groups: (( meta.security_groups ))
