meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: nxlog
    templates:
    - name: nxlog
      release: nxlog
    instances: 1
    persistent_disk: 0
    resource_pool: small_z1
    networks: (( merge ))

networks: (( merge ))

properties:
  nxlog:
    input:
      files:
        - { path: "/var/log/syslog", recursive: false, exclude: "" }
        - { path: "/var/log/dpkg.log", recursive: false, exclude: "" }
        - { path: "/var/log/messages", recursive: false, exclude: "" }
        - { path: "/var/vcap/data/sys/log/*.log", recursive: true, exclude: "(monit|nxlog)" }
